### ISSUE TITLE
CentOS 8 qemu-system-x86_64 replace as qmeu-kvm

### ISSUE THREAD

**Issue by AvengerMoJo** [OSInside/kiwi-boxed-plugin#27]
qemu-system-x86_64 doesn't exist in CentOS 8 anymore. 
It is replaced by /usr/libexec/qemu-kvm in qemu-kvm-core.rpm. 
We either need to adopt that and do  qemu-system-x86_64 runtime detection script or testing to see if new qemu-kvm existed.

**Comment by schaefi** [comment]
yes you are right, there should be a more robust way to call kvm in the desired arch
