### ISSUE TITLE
Permissions issues with the boxed-VMs storage

### ISSUE THREAD

**Issue by ellcs** [OSInside/kiwi-boxed-plugin#28]
The storage location of the boxed-VMs is currrently `/var/tmp/kiwi/boxes`. All users on a system share these boxes. This leads to conflicting permissions between users, when a box-VM is outdated and another user tries to update it.

First noted in #26.

### Expected behaviour

Either... 

- Tell the user to delete the boxes manually `rm -rf /var/tmp/kiwi/boxes`
- Use individual storage paths for every user.

### Steps to reproduce

1. Build a box as `root`.
2. Wait sometime for a box update. Inspect the date for e.g. `leap`:
    https://build.opensuse.org/project/show/Virtualization:Appliances:SelfContained:leap
3. Try a new build as another user, with lower privileges.

**Comment by schaefi** [comment]
Thanks, yep we should do this :+1:
