### ISSUE TITLE
Some boxes are no longer available

### ISSUE THREAD

**Issue by keto** [OSInside/kiwi-boxed-plugin#53]
It looks like the leap and universal boxes got removed by automated cleanup of repositories in OBS.

https://build.opensuse.org/request/show/1050474
https://build.opensuse.org/request/show/1053653

So now the boxbuild command gives error
`KiwiUriOpenError: http://download.opensuse.org/repositories/Virtualization:/Appliances:/SelfContained:/leap/images: 404 Client Error: Not Found`

**Comment by schaefi** [comment]
Thanks for reporting. Yes you are right the state of the box builds were broken. I have fixed the situation and they should now all be back online once OBS has finished its job.

I also fixed some incompatibilities in the box names according to the repos they actually get build for.
These name changes requires an update of the plugin (it provides the yaml config to know how to fetch from OBS).
Please fetch it via ```pip``` or from package updates:

* https://pypi.org/project/kiwi-boxed-plugin/

Thanks much
