### ISSUE TITLE
Not able to download leap box image

### ISSUE THREAD

**Issue by neilgierman** [OSInside/kiwi-boxed-plugin#63]
This worked 2 days ago, but not working today and I have had no changes to my config. I can only assume something changed on the openSUSE downloads side.

When I try to build an iso based on openSUSE leap 15.4, I am now getting a 403 from the download server when trying to download the self contained image. I get the same 403 when I try to directly browse to that URL from my browser.

Is there something I can change in my config files or is this something I cannot resolve on my end:

```
user@host:~$ pip show kiwi
Name: kiwi
Version: 9.25.16
Summary: KIWI - Appliance Builder (next generation)
Home-page: https://osinside.github.io/kiwi
Author: Marcus Schaefer
Author-email: ms@suse.com
License: GPLv3+
Location: /usr/local/lib/python3.10/dist-packages
Requires: docopt, lxml, PyYAML, requests, simplejson
Required-by: kiwi-boxed-plugin

user@host:~$ pip show kiwi_boxed_plugin
Name: kiwi-boxed-plugin
Version: 0.2.30
Summary: KIWI - Boxed Build Plugin
Home-page: https://github.com/OSInside/kiwi-boxed-plugin
Author: Marcus Schaefer
Author-email: ms@suse.com
License: GPLv3+
Location: /usr/local/lib/python3.10/dist-packages
Requires: cerberus, docopt, kiwi, progressbar2, PyYAML, requests
Required-by:

user@host:~$ kiwi-ng --type iso system boxbuild --box leap -- --description kiwi --target-dir output
[ INFO    ]: 13:14:23 | Reading box plugin config file: /usr/local/lib/python3.10/dist-packages/kiwi_boxed_plugin/config/kiwi_boxed_plugin.yml
[ INFO    ]: 13:14:23 | Validating kiwi_build_command_args:
    ['system', 'build', '--description', 'kiwi', '--target-dir', 'output']
[ INFO    ]: 13:14:23 | Building with:
    ['--type', 'iso', 'system', 'build', '--description', 'kiwi', '--target-dir', 'output']
[ ERROR   ]: 13:14:35 | KiwiUriOpenError: KiwiUriOpenError: http://download.opensuse.org/repositories/Virtualization:/Appliances:/SelfContained:/leap/images: 403 Client Error: Forbidden for url: http://downloadcontentcdn.opensuse.org/repositories/Virtualization:/Appliances:/SelfContained:/leap/images/ None
```

**Comment by neilgierman** [comment]
Note: If I edit my `/usr/local/lib/python3.10/dist-packages/kiwi_boxed_plugin/config/kiwi_boxed_plugin.yml` and change the `source` from using `obs://` to the direct `http://download.opensuse.org/repositories/`, it starts working. Not sure if that is a valid long-term solution.

**Comment by schaefi** [comment]
sorry for the very late response. I was looking at this and tested it today. The download of the box worked for me now. SUSE was performing a relocation of servers during the last month which has lead to some issues especially on the https vs. http download links. The obs:// mimetype resolves an https url and you switched it to http which worked in this particular situation. I think all these issues should be fixed now.

If you still have issues please re-open. Thanks
